# [KDT] ch1 데이타분석용 파이썬 이해

In [4]:
import os
os.getcwd()

'C:\\Users\\강지윤\\Desktop\\인공지능기초'

In [5]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
pd.__version__

'1.4.4'

# 1. Numpy

In [4]:
#import numpy 
import numpy

In [5]:
# nd array 1차원
a = np.array([1,2,3,['a']])
print(a)

[1 2 3 list(['a'])]


In [8]:
# nd array 2차원
np.arange(1,30,2)
np.array([[ 1,  3,  5,  7], [11, 13, 15, 17, 19]]).shape


(2,)

In [9]:
# nd array 3차원
np.array([[[ 1,  3,  5,  7,  9], [11, 13, 15, 17, 19]]]).shape

(1, 2, 5)

### 1_1. ndarray의 데이터 타입

In [10]:
# int type
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [14]:
# int type + object
list2 = [1,2,3.0,4.9,5,'test']
list3 = [1,2,3,4,5]
array2 = np.array(list2)
array3 = np.array(list3)
print(array2, array2.dtype,array3.dtype)
# int type + float


['1' '2' '3.0' '4.9' '5' 'test'] <U32 int32


In [15]:
# type 변환, astype('float'), astype('int')
array_int = np.arange(1,10)
array_float = np.arange(1,2,0.1)
print(array_float.dtype)

ee = array_int.astype('float')
print(ee,ee.dtype)

dd = array_float.astype('int')
print(dd, dd.dtype)

array_float



float64
[1. 2. 3. 4. 5. 6. 7. 8. 9.] float64
[1 1 1 1 1 1 1 1 1 1] int32


array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

### 1_2. ndarray를 편리하게 생성하기 - arange, zeros, ones

In [6]:
# np.arange
sequence_array = np.arange(1,12)

In [8]:
#(3, 2) shape을 가지는 모든 원소가 0, dtype은 int32 인 ndarray 생성. 
zero_array = np.zeros((3,2))
print('zero_array',zero_array)
#(3, 2) shape을 가지는 모든 원소가 1인 ndarray 생성.
one_array = np.ones((3,2))
print(one_array)
print(zero_array)

zero_array [[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


### 1_3. ndarray reshape

In [9]:
# reshape
array1 = np.arange(10)
array1.reshape(2,-1)
array1.reshape(5,-1)

# (2, 5) shape으로 변환
array2 = array1.reshape(2,-1)

#(5, 2) shape으로 변환
array3 = array1.reshape(5,-1)
print(array1)
print(array2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [148]:
# reshape (X)
array = array1.reshape(5,-1)
array


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
# reshape(-1)
reshape_ex = array1.reshape(2,-1)
reshape_ex

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
# reshape (X)
reshape_ex2 = array1.reshape(-1,2)
print(reshape_ex2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
# reshape (ndarray 차원변환) 
array1 = np.arange(8)
print( 'array1:\t',array1.tolist())
print('array1:\t', array1)

# 1차원 ndarray를 3차원 ndarray로 변환 
array3d = array1.reshape((2,2,-1))
print( 'array3d:\n',array3d.tolist())
print('array3d:\n', array3d)
print()
# 3차원 ndarray를 2차원 ndarray로 변환하되 칼럼갯수는 1 
array5 = array3d.reshape(-1,1)
print('array2d:\n',array5)

array5[0][0] = 100
print()
print('array5 : ', array5)
print()
print('array3d : ', array3d)
# 1차원 ndarray를 2차원 ndarray로 변환화되 칼럼 갯수는 1 

# 3차원 ndarray를 1차원으로 변환 

array1:	 [0, 1, 2, 3, 4, 5, 6, 7]
array1:	 [0 1 2 3 4 5 6 7]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array3d:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

array2d:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]

array5 :  [[100]
 [  1]
 [  2]
 [  3]
 [  4]
 [  5]
 [  6]
 [  7]]

array3d :  [[[100   1]
  [  2   3]]

 [[  4   5]
  [  6   7]]]


### 1_4. ndarray indexing

* 단일 값 추출 (1d array)

In [12]:
# 1에서 부터 12 까지의 1차원 ndarray 생성 
arr = np.arange(12)
print('arr=',arr)
arr[2]

arr= [ 0  1  2  3  4  5  6  7  8  9 10 11]


2

In [13]:
# array[-1] 맨 뒤값
arr[-1]

11

단일 값 추출 (2d array)

In [14]:
# 실습 array 생성
arr12 = np.arange(12)


In [15]:
# ndarray indexing
arr26 = arr12.reshape(2,6)
arr26[0,2]
arr26[1,3]

9

* 슬라이싱 - 연속된 인덱스상의 값을 추출하는 방식

In [187]:
# 실습 array 생성
arr12[0:3]


arr12 =  [ 0  1  2  3  4  5  6  7  8  9 10 11]


array([0, 1, 2])

In [188]:
# 슬라이싱 1d
print('arr12 = ',arr12)
arr12[0:3]


arr12 =  [ 0  1  2  3  4  5  6  7  8  9 10 11]


array([0, 1, 2])

In [207]:
# 슬라이싱 2d
print('arr26 = ', arr26)
arr26[0:,1:3]
arr26[:2 , :-2]

arr26 =  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


array([[0, 1, 2, 3],
       [6, 7, 8, 9]])

* 팬시 인덱싱 - 리스트나 ndarray로 인덱스 집합을 지정하는 방식

In [208]:
# 실습 array 생성
arr_12 = np.arange(12)
print('arr_12\n', arr_12)
arr_26 = arr_12.reshape(2,6)
print('arr_26\n', arr_26)
arr_34 = arr_12.reshape(3,-1)
print('arr_34\n', arr_34)

arr_12
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
arr_26
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
arr_34
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [212]:
# 팬시 인덱싱
arr_34[[0,2], :2]



array([[0, 1],
       [8, 9]])

* 불린 인덱싱- True, False 조건으로 인덱스 집합을 지정하는 방식

In [213]:
# 실습 array 생성
arr_12 = np.arange(12)
print('arr_12\n', arr_12)

arr_12
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [214]:
# 불린 인덱싱
arr12 > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True])

In [227]:
# 불린 인덱싱, boolean_indexes => boolean_indexes는 필터링에 활용
arr_12[arr>4]
arr_12[[False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True]]


array([ 5,  6,  7,  8,  9, 10, 11])

In [233]:
# arr_12를 2로 나눈 나머지가 짝수인가
np.mod(arr_12, 2) == 0


array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

In [245]:
# arr_12에서 홀수만 추출(필터링)

arr_12[arr_12%2==0]

array([ 0,  2,  4,  6,  8, 10])

연습문제 풀이

# 2. Pandas

### 2_1. DataFrames 생성

* pd.DataFrame() 

In [252]:
# list로 생성
list = [[1,2,3,4],[5,6,7,8]]
list
pd.DataFrame(list)

0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [253]:
# list로 생성, columnlumn 추가
pd.DataFrame(list, columns = ['A','B','C','D'])

A  B  C  D
0  1  2  3  4
1  5  6  7  8

In [255]:
# list로 생성, column 추가, indexex 추가

pd.DataFrame(list, columns = ['A','B','C','D'], index = ['one','two'])

A  B  C  D
one  1  2  3  4
two  5  6  7  8

In [260]:
# array로 생성
arr =  np.arange(12)
arr2 = arr.reshape(3,-1)
arr2
pd.DataFrame(arr2, columns = ['A','B','C','D'], index = ['one','two','three'])

A  B   C   D
one    0  1   2   3
two    4  5   6   7
three  8  9  10  11

In [ ]:
# array로 생성, column추가, index 추가


In [262]:
# 딕셔너리로 생성
dic = {'A':[1,2,3] ,'B':[4,5,6] ,'C':[7,8,9]}


In [263]:
# 딕셔너리로 생성, index 추가
pd.DataFrame(data = dic, index = ['one','two','three'])


A  B  C
one    1  4  7
two    2  5  8
three  3  6  9

* DataFrame을 넘파이 ndarray, list, 딕셔너리로 변환하기

In [265]:
# DataFrame 생성
df = pd.DataFrame(data = dic, index = ['one','two','three'])
df

A  B  C
one    1  4  7
two    2  5  8
three  3  6  9

In [268]:
# DataFrame을 딕셔너리로 변환
df.to_dict()

{'A': {'one': 1, 'two': 2, 'three': 3},
 'B': {'one': 4, 'two': 5, 'three': 6},
 'C': {'one': 7, 'two': 8, 'three': 9}}

In [271]:
# DataFrame을 ndarray로 변환
df.values

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int64)

In [272]:
# DataFrame을 list로 변환
df.values.tolist()

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

## Quiz 1

1) 아래 DataFrame을 딕셔너리로 생성하시오

In [277]:
pd.DataFrame({'name': ['kdh100','kdh101','kdh102','kdh103'], 'jumin7':['990623-2','900303-2','681205-2','931226-2'],'sex':['F','F','F','F']})

name    jumin7 sex
0  kdh100  990623-2   F
1  kdh101  900303-2   F
2  kdh102  681205-2   F
3  kdh103  931226-2   F

In [16]:
pd.DataFrame({'name':['kdh100','kdh101','kdh102','kdh103'], 'jumin':['990623-2','900303-2','681208-2','931226-2'],
             'sex':['F','F','F','F']})

name     jumin sex
0  kdh100  990623-2   F
1  kdh101  900303-2   F
2  kdh102  681208-2   F
3  kdh103  931226-2   F

### 2_2. Data Frame 읽기
* read_csv()** csv, txt, Excel Data 가능


* 데이터 읽어오기 pd.read_csv('file_name.csv')
- [데이터 읽어오기 참고(csv,txt,xlsx,UTF-8 인코딩)]
- df = pd.read_csv('file_name.csv')
- txt: 텍스트 파일. 특정 구분자로 구분되어있다면 sep 인자에 명시(탭(tab)은 sep='\t', '|' 는 sep='|'
- df = pd.read_csv('file_name.csv', encoding='cp949') - 한글파일 인코딩 에러시
- df = pd.read_csv('file_name.csv', sep='\t') - 구분자: Tab일때
                                        
- xlsx: 엑셀 파일. 특정 시트(sheet)의 데이터만 읽어올 경우 sheet_name 인자에 시트명 또는 순번을 입력해준다.
- df = pd.read_excel('file.xlsx')
- df = pd.read_excel('file.xlsx', sheet_name = 'first_sheet')

In [ ]:
import os
os.getcwd()

In [282]:
# 파일 로딩 (hk_221206.csv), 절대경로/상대경로 (.\\, ..\\)
# df_hk = pd.read_csv('.\\data\\hk_221206.csv') # df_hk 라는 dataFrame명을 생성
df_hk = pd.read_csv('./data/hk_221206.csv')

In [283]:
df_hk

name    jumin7 gender  height  age blood_type company grades  salary  \
0      hkd1  990623-2      F   161.9   22          A       A      A    4100   
1     hkd10  900303-2      F   169.4   31          A       A      B    4720   
2    hkd100  681205-2      F   168.3   55          A       A      B    7280   
3    hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4    hkd102  920123-1      M   188.6   29          O       B      F    4390   
..      ...       ...    ...     ...  ...        ...     ...    ...     ...   
245   hkd95  730710-2      F   157.8   50          A       A      A    6990   
246   hkd96  720805-2      F   150.4   51          O       A      A    7110   
247   hkd97  710929-1      M   172.4   52          A       A      B    8000   
248   hkd98  701024-1      M   166.7   53          O       A      B    8760   
249   hkd99  691115-2      F   152.6   54          B       A      B    7470   

     expenditure  
0           1975  
1           2970  
2           5905  
3           2935  
4           4015  
..           ...  
245         4865  
246         4985  
247         6625  
248         7385  
249         6095  

[250 rows x 10 columns]

In [285]:
df_hk.head(10)

name    jumin7 gender  height  age blood_type company grades  salary  \
0    hkd1  990623-2      F   161.9   22          A       A      A    4100   
1   hkd10  900303-2      F   169.4   31          A       A      B    4720   
2  hkd100  681205-2      F   168.3   55          A       A      B    7280   
3  hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4  hkd102  920123-1      M   188.6   29          O       B      F    4390   
5  hkd103  910215-2      F   150.2   30          A       B      A    3290   
6  hkd104  990623-1      M   176.0   22          A       B      A    3750   
7  hkd105  980717-2      F   163.4   23          B       B      B    3080   
8  hkd106  970818-1      M   186.3   24         AB       B      C    3110   
9  hkd107  960909-1      M   181.8   25          O       B      B    3230   

   expenditure  
0         1975  
1         2970  
2         5905  
3         2935  
4         4015  
5         1915  
6         2375  
7         1330  
8         2360  
9         1480

In [286]:
df_hk.tail(10)

name    jumin7 gender  height  age blood_type company grades  salary  \
240  hkd90  760328-1      M   172.4   45          B       A      A    7210   
241  hkd91  750423-1      M   170.7   46          A       A      F    6920   
242  hkd92  740518-2      F   170.8   47          B       A      B    6610   
243  hkd93  730719-1      M   180.4   48         AB       A      B    7560   
244  hkd94  720614-1      M   174.1   49          O       A      B    8540   
245  hkd95  730710-2      F   157.8   50          A       A      A    6990   
246  hkd96  720805-2      F   150.4   51          O       A      A    7110   
247  hkd97  710929-1      M   172.4   52          A       A      B    8000   
248  hkd98  701024-1      M   166.7   53          O       A      B    8760   
249  hkd99  691115-2      F   152.6   54          B       A      B    7470   

     expenditure  
240         5835  
241         6420  
242         5235  
243         6185  
244         7165  
245         4865  
246         4985  
247         6625  
248         7385  
249         6095

**head()와 tail()**

head()는 맨 앞부터 데이터 추출 (기본5개),    
tail()은 맨 뒤부터 데이터 추출 (기본5개)  

In [305]:
df_hk.index

RangeIndex(start=0, stop=250, step=1)

**DataFrame 출력 시 option**
* max_rows, max_columns, max_colwidth 설정


In [307]:
pd.set_option('display.max_rows',1000)
pd.set_option('display.max_columns',1000)
pd.set_option('display.max_colwidth',-1)
df_hk

name    jumin7 gender  height  age blood_type company grades  salary  \
0      hkd1  990623-2      F   161.9   22          A       A      A    4100   
1     hkd10  900303-2      F   169.4   31          A       A      B    4720   
2    hkd100  681205-2      F   168.3   55          A       A      B    7280   
3    hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4    hkd102  920123-1      M   188.6   29          O       B      F    4390   
5    hkd103  910215-2      F   150.2   30          A       B      A    3290   
6    hkd104  990623-1      M   176.0   22          A       B      A    3750   
7    hkd105  980717-2      F   163.4   23          B       B      B    3080   
8    hkd106  970818-1      M   186.3   24         AB       B      C    3110   
9    hkd107  960909-1      M   181.8   25          O       B      B    3230   
10   hkd108  951015-1      M   170.1   26          A       B      B    3410   
11   hkd109  941105-1      M   177.8   27          O       B      B    3420   
12    hkd11  890419-1      M   188.2   32          B       A      B    4820   
13   hkd110  931225-2      F   163.2   28          A       B      B    3460   
14   hkd111  920122-2      F   156.5   29          O       B      C    4370   
15   hkd112  910113-2      F   166.2   30          B       B      D    3260   
16   hkd113  900303-2      F   161.9   31          A       B      D    3540   
17   hkd114  890419-2      F   157.5   32          B       B      A    4040   
18   hkd115  880909-2      F   158.6   33         AB       B      B    5230   
19   hkd116  870118-1      M   173.9   34          O       B      D    4590   
20   hkd117  860117-2      F   163.0   35          A       B      A    4730   
21   hkd118  851214-2      F   164.9   36          O       B      A    4950   
22   hkd119  840717-2      F   153.7   37          A       B      A    4450   
23    hkd12  881109-2      F   170.2   33         AB       A      A    5080   
24   hkd120  830831-1      M   183.8   38          O       B      A    5660   
25   hkd121  820904-2      F   153.3   39          B       B      B    6060   
26   hkd122  811023-1      M   171.9   40          A       B      A    6130   
27   hkd123  800329-1      M   184.6   41          B       B      B    6050   
28   hkd124  791214-1      M   181.1   42         AB       B      A    6250   
29   hkd125  780112-2      F   169.1   43          O       B      A    5710   
30   hkd126  770201-1      M   190.4   44          A       B      A    6210   
31   hkd127  760325-2      F   163.1   45          O       B      B    6920   
32   hkd128  750430-2      F   148.1   46          A       B      B    7000   
33   hkd129  740530-1      M   184.4   47          O       B      B    7420   
34    hkd13  870718-1      M   180.5   34          O       A      A    4990   
35   hkd130  730726-1      M   175.2   48          B       B      B    7000   
36   hkd131  720611-2      F   156.6   49          A       B      A    7250   
37   hkd132  730706-1      M   181.5   50          B       B      B    7420   
38   hkd133  720801-2      F   149.5   51         AB       B      B    7460   
39   hkd134  710925-1      M   182.2   52          O       B      C    7250   
40   hkd135  701020-1      M   190.6   53          A       B      D    7430   
41   hkd136  690111-2      F   164.7   54          O       B      C    6440   
42   hkd137  681231-1      M   182.9   55          A       B      B    8460   
43   hkd138  910213-2      F   168.8   30          O       B      A    4060   
44   hkd139  900330-1      M   172.0   31          B       B      C    3530   
45    hkd14  860617-1      M   176.8   35          A       A      A    5070   
46   hkd140  890419-1      M   186.4   32          A       B      A    3680   
47   hkd141  880509-1      M   180.9   33          B       B      C    3860   
48   hkd142  870618-1      M   181.3   34         AB       B      A    4580   
49   hkd143  860630-1      M   181.6   35          O     

In [309]:
pd.set_option('display.max_rows',50)
pd.set_option('display.max_columns',50)
pd.set_option('display.max_colwidth',-1)
df_hk

name    jumin7 gender  height  age blood_type company grades  salary  \
0    hkd1    990623-2  F      161.9   22   A          A       A      4100     
1    hkd10   900303-2  F      169.4   31   A          A       B      4720     
2    hkd100  681205-2  F      168.3   55   A          A       B      7280     
3    hkd101  931226-2  F      155.3   28   AB         B       B      4060     
4    hkd102  920123-1  M      188.6   29   O          B       F      4390     
..      ...       ... ..        ...   ..  ..         ..      ..       ...     
245  hkd95   730710-2  F      157.8   50   A          A       A      6990     
246  hkd96   720805-2  F      150.4   51   O          A       A      7110     
247  hkd97   710929-1  M      172.4   52   A          A       B      8000     
248  hkd98   701024-1  M      166.7   53   O          A       B      8760     
249  hkd99   691115-2  F      152.6   54   B          A       B      7470     

     expenditure  
0    1975         
1    2970         
2    5905         
3    2935         
4    4015         
..    ...         
245  4865         
246  4985         
247  6625         
248  7385         
249  6095         

[250 rows x 10 columns]

## Quiz 2

1) bike.csv를 읽고 column이 몇 개 인지 기술 하시오

2) iris.cvs를 읽고 row가 몇 개 인지 기술 하시오 

3) Online2.txt를 읽고 3번째 column이 무엇인지 기술 하시오 

In [315]:
df_bike = pd.read_csv('./data/bike.csv')
df_iris = pd.read_csv('./data/iris.csv')
df_Online2 = pd.read_csv('./data/Online2.txt',sep = '\t')

In [319]:
len(df_bike.columns)

12

In [320]:
len(df_iris)

150

In [318]:
df_Online2.columns[2]

'Description'

### 2_3. DataFrame 속성(attribute)
* df.ndim: 객체의 차원
* df.shape: 각 차원의 길이
* df.dtypes: 데이터 타입 dtype와 구별, 복수형이라야 함
* df.info(): 데이터 타입 정보 요약, 결측치 정보
* df.columns: column명
* df.describe(): 수치형 데이터 요약 정보

In [18]:
df_hk = pd.read_csv('./data/hk_221206.csv')

In [19]:
# df.ndim: 객체의 차원
df_hk.ndim

2

In [20]:
# df.shape: 각 차원의 길이
df_hk.shape

(250, 10)

In [22]:
# df.dtypes: 데이터 타입 dtype와 구별, 복수형이라야 함
df_hk.dtypes

name            object
jumin7          object
gender          object
height         float64
age              int64
blood_type      object
company         object
grades          object
salary           int64
expenditure      int64
dtype: object

In [23]:
# df.info(): 데이터 타입 정보 요약, 결측치 정보
df_hk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   name         250 non-null    object 
 1   jumin7       250 non-null    object 
 2   gender       250 non-null    object 
 3   height       250 non-null    float64
 4   age          250 non-null    int64  
 5   blood_type   250 non-null    object 
 6   company      250 non-null    object 
 7   grades       250 non-null    object 
 8   salary       250 non-null    int64  
 9   expenditure  250 non-null    int64  
dtypes: float64(1), int64(3), object(6)
memory usage: 19.7+ KB


In [24]:
# df.columns: column명
col_list = df_hk.columns
col_list

Index(['name', 'jumin7', 'gender', 'height', 'age', 'blood_type', 'company',
       'grades', 'salary', 'expenditure'],
      dtype='object')

In [31]:
# df.describe(): 수치형 데이터 요약 정보
df_hk.describe()

height         age        salary   expenditure
count  250.000000  250.000000    250.000000    250.000000
mean   169.569200   39.240000   6357.480000   4971.480000
std     12.283857    8.653899   1849.791383   1861.112508
min    148.100000   20.000000   3080.000000   1330.000000
25%    159.300000   33.000000   5002.500000   3593.750000
50%    168.750000   39.000000   6100.000000   4762.500000
75%    180.375000   46.000000   7427.500000   6272.500000
max    191.800000   55.000000  11990.000000  10865.000000

In [30]:
# df.describe(): all 데이터 요약 정보
df_hk.describe(include = 'all')

name    jumin7 gender      height         age blood_type company  \
count    250       250    250  250.000000  250.000000        250     250   
unique   250       240      2         NaN         NaN          4       3   
top     hkd1  890419-1      M         NaN         NaN          A       A   
freq       1         3    138         NaN         NaN         84     100   
mean     NaN       NaN    NaN  169.569200   39.240000        NaN     NaN   
std      NaN       NaN    NaN   12.283857    8.653899        NaN     NaN   
min      NaN       NaN    NaN  148.100000   20.000000        NaN     NaN   
25%      NaN       NaN    NaN  159.300000   33.000000        NaN     NaN   
50%      NaN       NaN    NaN  168.750000   39.000000        NaN     NaN   
75%      NaN       NaN    NaN  180.375000   46.000000        NaN     NaN   
max      NaN       NaN    NaN  191.800000   55.000000        NaN     NaN   

       grades        salary   expenditure  
count     250    250.000000    250.000000  
unique      5           NaN           NaN  
top         B           NaN           NaN  
freq      116           NaN           NaN  
mean      NaN   6357.480000   4971.480000  
std       NaN   1849.791383   1861.112508  
min       NaN   3080.000000   1330.000000  
25%       NaN   5002.500000   3593.750000  
50%       NaN   6100.000000   4762.500000  
75%       NaN   7427.500000   6272.500000  
max       NaN  11990.000000  10865.000000

### 2_4. Index와 Column 객체

In [32]:
# 파일 로딩 
df_hk = pd.read_csv('./data/hk_221206.csv')
df_hk[-100:]

name    jumin7 gender  height  age blood_type company grades  salary  \
150  hkd234  880513-2      F   150.7   33         AB       C      B    8450   
151  hkd235  870622-2      F   153.5   34          O       C      A   10800   
152  hkd236  860621-1      M   166.2   35          A       C      B   10410   
153  hkd237  850118-2      F   160.7   36          O       C      B   10480   
154  hkd238  840720-2      F   156.8   37          A       C      B    9380   
..      ...       ...    ...     ...  ...        ...     ...    ...     ...   
245   hkd95  730710-2      F   157.8   50          A       A      A    6990   
246   hkd96  720805-2      F   150.4   51          O       A      A    7110   
247   hkd97  710929-1      M   172.4   52          A       A      B    8000   
248   hkd98  701024-1      M   166.7   53          O       A      B    8760   
249   hkd99  691115-2      F   152.6   54          B       A      B    7470   

     expenditure  
150         7325  
151         8675  
152         9285  
153         9355  
154         8255  
..           ...  
245         4865  
246         4985  
247         6625  
248         7385  
249         6095  

[100 rows x 10 columns]

In [33]:
# Index, column 보기
df_hk.index
#df = df.reset_index(drop=True)

RangeIndex(start=0, stop=250, step=1)

In [35]:
# Index 객체 추출 (전체)
df_hk.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [36]:
# Index 객체 추출 (일부)
df_hk.index.values[:50]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=int64)

In [367]:
# column 객체 추출
df_hk.columns

Index(['name', 'jumin7', 'gender', 'height', 'age', 'blood_type', 'company',
       'grades', 'salary', 'expenditure'],
      dtype='object')

In [37]:
# column 객체 추출 (일부)
df_hk.columns[2:5]

Index(['gender', 'height', 'age'], dtype='object')

In [38]:
# column 내용 추출 (1개)
df_hk['age']

0      22
1      31
2      55
3      28
4      29
       ..
245    50
246    51
247    52
248    53
249    54
Name: age, Length: 250, dtype: int64

In [41]:
# column 내용 추출 (2개 이상)
df_hk[df_hk.columns[2:5]]

gender  height  age
0        F   161.9   22
1        F   169.4   31
2        F   168.3   55
3        F   155.3   28
4        M   188.6   29
..     ...     ...  ...
245      F   157.8   50
246      F   150.4   51
247      M   172.4   52
248      M   166.7   53
249      F   152.6   54

[250 rows x 3 columns]

## Quiz 3

1) bike.csv의 column을 전부 기술 하시오

2) iris.cvs의 정수형 변수는 몇 개 인지 기술 하시오

In [63]:
df_bike = pd.read_csv('./data/bike.csv')
#1
print('1:',df_bike.columns.values)
df_iris = pd.read_csv('./data/iris.csv')
print(len(df_iris.columns[df_iris.dtypes == 'float']))



1: ['datetime' 'season' 'holiday' 'workingday' 'weather' 'temp' 'atemp'
 'humidity' 'windspeed' 'casual' 'registered' 'count']
4
float64


### 2_5. 함수 및 메소드
* df['age'].mean(): 평균값
* df['age'].median(): 중앙값
* df['age'].min(): 최소값
* df['age'].max(): 최대값
* df['age'].var(): 분산
* df['age'].std(): 표준편차
* df['age'].skew(): 왜도
* df['age'].kurt(): 첨도
* df['age'].count(): 개체수
* df['age'].quantile(q = 0.25) : 1사분위수

In [64]:
# 수치형변수 함수 및 메소드
print( "df_hk['age'].min() : ", df_hk['age'].min())
print( "df_hk['age'].max() : ", df_hk['age'].max())
print( "df_hk['age'].var() : ", df_hk['age'].var())
print( "df_hk['age'].std() : ", df_hk['age'].std())
print( "df_hk['age'].skew() : ", df_hk['age'].skew())
print( "df_hk['age'].kurt() : ", df_hk['age'].kurt())

df_hk['age'].min() :  20
df_hk['age'].max() :  55
df_hk['age'].var() :  74.88995983935737
df_hk['age'].std() :  8.653898534149645
df_hk['age'].skew() :  -0.07707060633056183
df_hk['age'].kurt() :  -0.7894949277134797


* df['blood_type'].nunique(): Column내 개별 데이터값 갯수
* df['blood_type'].unique(): Column내 개별 데이터값 내용
* df['blood_type'].value_counts(): Column내 개별 데이터값의 분포

  주의) default는 Null 값 제외, Null값 포함하려면 dropna를 True로 세팅

In [68]:
# 명목형변수 함수 및 메소드
print(df_hk['gender'].value_counts())
print(df_hk['blood_type'].unique())
print(df_hk['blood_type'].value_counts())

M    138
F    112
Name: gender, dtype: int64
['A' 'AB' 'O' 'B']
A     84
O     83
B     54
AB    29
Name: blood_type, dtype: int64


## Quiz 4

1) iris.cvs의 column('species')의 value_counts()를 구하시오

2) Online2.txt의 column('Country')의 unique()를 구하시오

In [75]:
df_Online2 = pd.read_csv('./data/Online2.txt',sep='\t')

print(df_iris['species'].value_counts())
print(df_Online2['Country'].unique())

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64
['United Kingdom' 'France' 'Australia' 'Netherlands' 'Germany' 'Norway'
 'EIRE' 'Switzerland' 'Spain' 'Poland' 'Portugal' 'Italy' 'Belgium'
 'Lithuania' 'Japan' 'Iceland' 'Channel Islands' 'Denmark' 'Cyprus'
 'Sweden' 'Austria' 'Israel' 'Finland' 'Bahrain' 'Greece' 'Hong Kong'
 'Singapore' 'Lebanon' 'United Arab Emirates' 'Saudi Arabia'
 'Czech Republic' 'Canada' 'Unspecified' 'Brazil' 'USA'
 'European Community' 'Malta' 'RSA']


### 2_6. column 생성, 수정, 삭제


In [88]:
# column 생성
df_hk[:2]
df_hk['point'] = df_hk['expenditure']/100
df_hk['point'] = df_hk['point'].astype(int)

In [77]:
# column 수정
df_hk.head(10)

name    jumin7 gender  height  age blood_type company grades  salary  \
0    hkd1  990623-2      F   161.9   22          A       A      A    4100   
1   hkd10  900303-2      F   169.4   31          A       A      B    4720   
2  hkd100  681205-2      F   168.3   55          A       A      B    7280   
3  hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4  hkd102  920123-1      M   188.6   29          O       B      F    4390   
5  hkd103  910215-2      F   150.2   30          A       B      A    3290   
6  hkd104  990623-1      M   176.0   22          A       B      A    3750   
7  hkd105  980717-2      F   163.4   23          B       B      B    3080   
8  hkd106  970818-1      M   186.3   24         AB       B      C    3110   
9  hkd107  960909-1      M   181.8   25          O       B      B    3230   

   expenditure  point  
0         1975     19  
1         2970     29  
2         5905     59  
3         2935     29  
4         4015     40  
5         1915     19  
6         2375     23  
7         1330     13  
8         2360     23  
9         1480     14

In [78]:
df_hk['age'] + df_hk['salary']/100

0       63.0
1       78.2
2      127.8
3       68.6
4       72.9
       ...  
245    119.9
246    122.1
247    132.0
248    140.6
249    128.7
Length: 250, dtype: float64

**axis에 따른 삭제**

axis=1 일 경우 drop()은 column 방향으로 삭제

In [79]:
# 1개 column 삭제
# df_hk = df_hk.drop('point',axis = 1)
#inplace를 true로 주면 df_hk에 저장하지 않아도 본 데이터프레임에 반영이된다.
df_hk.head(10)

name    jumin7 gender  height  age blood_type company grades  salary  \
0    hkd1  990623-2      F   161.9   22          A       A      A    4100   
1   hkd10  900303-2      F   169.4   31          A       A      B    4720   
2  hkd100  681205-2      F   168.3   55          A       A      B    7280   
3  hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4  hkd102  920123-1      M   188.6   29          O       B      F    4390   
5  hkd103  910215-2      F   150.2   30          A       B      A    3290   
6  hkd104  990623-1      M   176.0   22          A       B      A    3750   
7  hkd105  980717-2      F   163.4   23          B       B      B    3080   
8  hkd106  970818-1      M   186.3   24         AB       B      C    3110   
9  hkd107  960909-1      M   181.8   25          O       B      B    3230   

   expenditure  point  
0         1975     19  
1         2970     29  
2         5905     59  
3         2935     29  
4         4015     40  
5         1915     19  
6         2375     23  
7         1330     13  
8         2360     23  
9         1480     14

In [82]:
# 2개 이상 column 삭제는 list로 입력. inplace=True일 경우 호출을 한 DataFrame에 drop결과가 직접 반영 
df_drop = df_hk.drop(df_hk.columns[0:3],axis = 1)


axis=0 일 경우 drop()은 row 방향으로 삭제 

In [85]:
# 1개 row 삭제
df_drop.drop(0, axis=0)


height  age blood_type company grades  salary  expenditure  point
1     169.4   31          A       A      B    4720         2970     29
2     168.3   55          A       A      B    7280         5905     59
3     155.3   28         AB       B      B    4060         2935     29
4     188.6   29          O       B      F    4390         4015     40
5     150.2   30          A       B      A    3290         1915     19
..      ...  ...        ...     ...    ...     ...          ...    ...
245   157.8   50          A       A      A    6990         4865     48
246   150.4   51          O       A      A    7110         4985     49
247   172.4   52          A       A      B    8000         6625     66
248   166.7   53          O       A      B    8760         7385     73
249   152.6   54          B       A      B    7470         6095     60

[249 rows x 8 columns]

In [84]:
# 2개 이상 row 삭제
df_drop.drop([0,1,2,3],axis = 0)

height  age blood_type company grades  salary  expenditure  point
4     188.6   29          O       B      F    4390         4015     40
5     150.2   30          A       B      A    3290         1915     19
6     176.0   22          A       B      A    3750         2375     23
7     163.4   23          B       B      B    3080         1330     13
8     186.3   24         AB       B      C    3110         2360     23
..      ...  ...        ...     ...    ...     ...          ...    ...
245   157.8   50          A       A      A    6990         4865     48
246   150.4   51          O       A      A    7110         4985     49
247   172.4   52          A       A      B    8000         6625     66
248   166.7   53          O       A      B    8760         7385     73
249   152.6   54          B       A      B    7470         6095     60

[246 rows x 8 columns]

column명 변경

In [86]:
# rename
df_hk.rename(columns={'gender': 'sex'})


name    jumin7 sex  height  age blood_type company grades  salary  \
0      hkd1  990623-2   F   161.9   22          A       A      A    4100   
1     hkd10  900303-2   F   169.4   31          A       A      B    4720   
2    hkd100  681205-2   F   168.3   55          A       A      B    7280   
3    hkd101  931226-2   F   155.3   28         AB       B      B    4060   
4    hkd102  920123-1   M   188.6   29          O       B      F    4390   
..      ...       ...  ..     ...  ...        ...     ...    ...     ...   
245   hkd95  730710-2   F   157.8   50          A       A      A    6990   
246   hkd96  720805-2   F   150.4   51          O       A      A    7110   
247   hkd97  710929-1   M   172.4   52          A       A      B    8000   
248   hkd98  701024-1   M   166.7   53          O       A      B    8760   
249   hkd99  691115-2   F   152.6   54          B       A      B    7470   

     expenditure  point  
0           1975     19  
1           2970     29  
2           5905     59  
3           2935     29  
4           4015     40  
..           ...    ...  
245         4865     48  
246         4985     49  
247         6625     66  
248         7385     73  
249         6095     60  

[250 rows x 11 columns]

In [90]:
# df.columns
df_hk.drop(['point'],axis = 1,inplace=True)
df_hk.columns = ['name', 'jumin7', 'gender', 'height', 'age', 'blood_type', 'company',
       'grades', 'salary', 'expenditure']

df_hk

name    jumin7 gender  height  age blood_type company grades  salary  \
0      hkd1  990623-2      F   161.9   22          A       A      A    4100   
1     hkd10  900303-2      F   169.4   31          A       A      B    4720   
2    hkd100  681205-2      F   168.3   55          A       A      B    7280   
3    hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4    hkd102  920123-1      M   188.6   29          O       B      F    4390   
..      ...       ...    ...     ...  ...        ...     ...    ...     ...   
245   hkd95  730710-2      F   157.8   50          A       A      A    6990   
246   hkd96  720805-2      F   150.4   51          O       A      A    7110   
247   hkd97  710929-1      M   172.4   52          A       A      B    8000   
248   hkd98  701024-1      M   166.7   53          O       A      B    8760   
249   hkd99  691115-2      F   152.6   54          B       A      B    7470   

     expenditure  
0           1975  
1           2970  
2           5905  
3           2935  
4           4015  
..           ...  
245         4865  
246         4985  
247         6625  
248         7385  
249         6095  

[250 rows x 10 columns]

## Quiz 5

1) iris.cvs의 column('sepal_length' , 'sepal_width')의 숫자 합을  파생변수 'sepal'로 생성하시오

In [92]:
df_iris['sepal'] = df_iris['sepal_length'] + df_iris['sepal_width']

In [93]:
df_iris

sepal_length  sepal_width  petal_length  petal_width    species  sepal
0             5.1          3.5           1.4          0.2     setosa    8.6
1             4.9          3.0           1.4          0.2     setosa    7.9
2             4.7          3.2           1.3          0.2     setosa    7.9
3             4.6          3.1           1.5          0.2     setosa    7.7
4             5.0          3.6           1.4          0.2     setosa    8.6
..            ...          ...           ...          ...        ...    ...
145           6.7          3.0           5.2          2.3  virginica    9.7
146           6.3          2.5           5.0          1.9  virginica    8.8
147           6.5          3.0           5.2          2.0  virginica    9.5
148           6.2          3.4           5.4          2.3  virginica    9.6
149           5.9          3.0           5.1          1.8  virginica    8.9

[150 rows x 6 columns]

In [101]:
np.array([1,2,3])+np.array([[1,3,4],[2,5,6]])

array([[2, 5, 7],
       [3, 7, 9]])

### 2_7. 인덱싱 및 필터링

* DataFrame [ ] 로 row와 column을 인덱싱

In [102]:
# 파일 로딩 
df_hk = pd.read_csv('./data/hk_221206.csv')
df_hk[:2]

name    jumin7 gender  height  age blood_type company grades  salary  \
0   hkd1  990623-2      F   161.9   22          A       A      A    4100   
1  hkd10  900303-2      F   169.4   31          A       A      B    4720   

   expenditure  
0         1975  
1         2970

In [103]:
# []에 한개의 column만 입력하면 Series 객체를 반환  
df_hk['age']

0      22
1      31
2      55
3      28
4      29
       ..
245    50
246    51
247    52
248    53
249    54
Name: age, Length: 250, dtype: int64

In [104]:
# []에 여러개 column을 list로 입력하면 column들로 구성된 DataFrame을 반환  
df_hk[df_hk.columns[0:2]]


name    jumin7
0      hkd1  990623-2
1     hkd10  900303-2
2    hkd100  681205-2
3    hkd101  931226-2
4    hkd102  920123-1
..      ...       ...
245   hkd95  730710-2
246   hkd96  720805-2
247   hkd97  710929-1
248   hkd98  701024-1
249   hkd99  691115-2

[250 rows x 2 columns]

In [446]:
# []에 한개 index 정보를 입력하면 DataFrame을 반환  
df_hk[2:5]

name    jumin7 gender  height  age blood_type company grades  salary  \
2  hkd100  681205-2  F      168.3   55   A          A       B      7280     
3  hkd101  931226-2  F      155.3   28   AB         B       B      4060     
4  hkd102  920123-1  M      188.6   29   O          B       F      4390     

   expenditure  
2  5905         
3  2935         
4  4015

In [107]:
# []에 한개 index 정보를 입력하면 DataFrame을 반환  
df_hk[0:1]

name    jumin7 gender  height  age blood_type company grades  salary  \
0  hkd1  990623-2      F   161.9   22          A       A      A    4100   

   expenditure  
0         1975

In [447]:
# []에 index 정보입력 오류
df_hk[3]

KeyError: 3

* iloc[ ] integer location : 위치기반 indexing

   [row정보, column정보] row, column 정보는 integer

In [108]:
# iloc
df_hk.iloc[[0,3,5,7],[3,5,7]]
#fancy indexing 가능
#컬럼정보가 인티저로만 들어가야한다

height blood_type grades
0   161.9          A      A
3   155.3         AB      B
5   150.2          A      A
7   163.4          B      B

* loc[ ] location : 명칭기반 indexing (slice indexing)

   [row정보, column정보] column 정보는 column명

In [109]:
# loc
df_hk.loc[0:3, 'name':'age']


name    jumin7 gender  height  age
0    hkd1  990623-2      F   161.9   22
1   hkd10  900303-2      F   169.4   31
2  hkd100  681205-2      F   168.3   55
3  hkd101  931226-2      F   155.3   28

In [110]:
df_hk['age']>30

0      False
1       True
2       True
3      False
4      False
       ...  
245     True
246     True
247     True
248     True
249     True
Name: age, Length: 250, dtype: bool

* boolean indexing

In [121]:
df_hk.loc[df_hk['age']>30,'salary']


1      4720
2      7280
12     4820
16     3540
17     4040
       ... 
245    6990
246    7110
247    8000
248    8760
249    7470
Name: salary, Length: 205, dtype: int64

In [479]:
df_hk.dtypes[1]
df_hk

name    jumin7 gender  height  age blood_type company grades  salary  \
0    hkd1    990623-2  F      161.9   22   A          A       A      4100     
1    hkd10   900303-2  F      169.4   31   A          A       B      4720     
2    hkd100  681205-2  F      168.3   55   A          A       B      7280     
3    hkd101  931226-2  F      155.3   28   AB         B       B      4060     
4    hkd102  920123-1  M      188.6   29   O          B       F      4390     
..      ...       ... ..        ...   ..  ..         ..      ..       ...     
245  hkd95   730710-2  F      157.8   50   A          A       A      6990     
246  hkd96   720805-2  F      150.4   51   O          A       A      7110     
247  hkd97   710929-1  M      172.4   52   A          A       B      8000     
248  hkd98   701024-1  M      166.7   53   O          A       B      8760     
249  hkd99   691115-2  F      152.6   54   B          A       B      7470     

     expenditure  
0    1975         
1    2970         
2    5905         
3    2935         
4    4015         
..    ...         
245  4865         
246  4985         
247  6625         
248  7385         
249  6095         

[250 rows x 10 columns]

## Quiz 6

1) iris.cvs의 column('petal_width') 값이 1.0보다 큰 것은 몇개인지 구하시오

2) bike.cvs의 column dtype이 'int64' 인것만 추출하고 DataFrame명을 'df_bike_int64'로 저장 하시오 

In [128]:
len(df_iris[df_iris['petal_width'] > 1.0])

93

In [146]:
df_bike.loc[: , df_bike.dtypes == 'int64']

season  holiday  workingday  weather  humidity  casual  registered  \
0           1        0           0        1        81       3          13   
1           1        0           0        1        80       8          32   
2           1        0           0        1        80       5          27   
3           1        0           0        1        75       3          10   
4           1        0           0        1        75       0           1   
...       ...      ...         ...      ...       ...     ...         ...   
10881       4        0           1        1        50       7         329   
10882       4        0           1        1        57      10         231   
10883       4        0           1        1        61       4         164   
10884       4        0           1        1        61      12         117   
10885       4        0           1        1        66       4          84   

       count  
0         16  
1         40  
2         32  
3         13  
4          1  
...      ...  
10881    336  
10882    241  
10883    168  
10884    129  
10885     88  

[10886 rows x 8 columns]

In [161]:

df_bike.loc[:,df_bike.dtypes == 'int64']
df_bike.dtypes == 'int64'

datetime      False
season         True
holiday        True
workingday     True
weather        True
temp          False
atemp         False
humidity       True
windspeed     False
casual         True
registered     True
count          True
dtype: bool

In [166]:
IntCol = []
for i in range(len(df_bike.columns)):
    if df_bike.dtypes[i] == 'int64':
        IntCol.append(df_bike.columns[i])
        
print(IntCol)


df_bike_int64 = df_bike[IntCol]
df_bike_int64

['season', 'holiday', 'workingday', 'weather', 'humidity', 'casual', 'registered', 'count']


season  holiday  workingday  weather  humidity  casual  registered  \
0           1        0           0        1        81       3          13   
1           1        0           0        1        80       8          32   
2           1        0           0        1        80       5          27   
3           1        0           0        1        75       3          10   
4           1        0           0        1        75       0           1   
...       ...      ...         ...      ...       ...     ...         ...   
10881       4        0           1        1        50       7         329   
10882       4        0           1        1        57      10         231   
10883       4        0           1        1        61       4         164   
10884       4        0           1        1        61      12         117   
10885       4        0           1        1        66       4          84   

       count  
0         16  
1         40  
2         32  
3         13  
4          1  
...      ...  
10881    336  
10882    241  
10883    168  
10884    129  
10885     88  

[10886 rows x 8 columns]

## Quiz 7

(실습문제 유형1을 사용하여, : indian_food2.csv (구분자: 쉼표(,), 255 행, 10 컬럼)

1) 단계 1-1. 지역(state) 컬럼을 제거하시오.

2) 단계 1-2. 조리 시간(cook_time)과 재료 준비 시간(prep_time)이 양수(>0)인 데이터만 추출하시오.

In [167]:
import pandas as pd
df_indial_food2 = pd.read_csv('./data/indian_food2.csv')
df_indial_food2.columns
df_indial_food2.drop('state', axis = 1)

id            name                                        ingredients  \
0      1      Balu shahi                    Maida flour, yogurt, oil, sugar   
1      2          Boondi                            Gram flour, ghee, sugar   
2      3  Gajar ka halwa       Carrots, milk, sugar, ghee, cashews, raisins   
3      4          Ghevar  Flour, ghee, kewra, milk, clarified butter, su...   
4      5     Gulab jamun  Milk powder, plain flour, baking powder, ghee,...   
..   ...             ...                                                ...   
250  251       Til Pitha            Glutinous rice, black sesame seeds, gur   
251  252         Bebinca  Coconut milk, egg yolks, clarified butter, all...   
252  253          Shufta  Cottage cheese, dry dates, dried rose petals, ...   
253  254       Mawa Bati  Milk powder, dry fruits, arrowroot powder, all...   
254  255          Pinaca  Brown rice, fennel seeds, grated coconut, blac...   

           diet  prep_time  cook_time flavor_profile   course      region  
0    vegetarian         45         25          sweet  dessert        East  
1    vegetarian         80         30          sweet  dessert        West  
2    vegetarian         15         60          sweet  dessert       North  
3    vegetarian         15         30          sweet  dessert        West  
4    vegetarian         15         40          sweet  dessert        East  
..          ...        ...        ...            ...      ...         ...  
250  vegetarian          5         30          sweet  dessert  North East  
251  vegetarian         20         60          sweet  dessert        West  
252  vegetarian         -1         -1          sweet  dessert       North  
253  vegetarian         20         45          sweet  dessert     Central  
254  vegetarian         -1         -1          sweet  dessert        West  

[255 rows x 9 columns]

In [168]:
df_indial_food2.loc[df_indial_food2['cook_time'] > 0 & df_indial_food2['prep_time'],:]

id               name  \
0      1         Balu shahi   
1      2             Boondi   
2      3     Gajar ka halwa   
3      4             Ghevar   
4      5        Gulab jamun   
..   ...                ...   
247  248  Prawn malai curry   
249  250             Shukto   
250  251          Til Pitha   
251  252            Bebinca   
253  254          Mawa Bati   

                                           ingredients            diet  \
0                      Maida flour, yogurt, oil, sugar      vegetarian   
1                              Gram flour, ghee, sugar      vegetarian   
2         Carrots, milk, sugar, ghee, cashews, raisins      vegetarian   
3    Flour, ghee, kewra, milk, clarified butter, su...      vegetarian   
4    Milk powder, plain flour, baking powder, ghee,...      vegetarian   
..                                                 ...             ...   
247      Coconut milk, prawns, garlic, turmeric, sugar  non vegetarian   
249  Green beans, bitter gourd, ridge gourd, banana...      vegetarian   
250            Glutinous rice, black sesame seeds, gur      vegetarian   
251  Coconut milk, egg yolks, clarified butter, all...      vegetarian   
253  Milk powder, dry fruits, arrowroot powder, all...      vegetarian   

     prep_time  cook_time flavor_profile       course           state  \
0           45         25          sweet      dessert     West Bengal   
1           80         30          sweet      dessert       Rajasthan   
2           15         60          sweet      dessert          Punjab   
3           15         30          sweet      dessert       Rajasthan   
4           15         40          sweet      dessert     West Bengal   
..         ...        ...            ...          ...             ...   
247         15         50          spicy  main course     West Bengal   
249         10         20          spicy  main course     West Bengal   
250          5         30          sweet      dessert           Assam   
251         20         60          sweet      dessert             Goa   
253         20         45          sweet      dessert  Madhya Pradesh   

         region  
0          East  
1          West  
2         North  
3          West  
4          East  
..          ...  
247        East  
249        East  
250  North East  
251        West  
253     Central  

[227 rows x 10 columns]

In [11]:
df_indial_food2.loc[(df_indial_food2['cook_time']> 0 )& (df_indial_food2['prep_time']>0),:]

id               name  \
0      1         Balu shahi   
1      2             Boondi   
2      3     Gajar ka halwa   
3      4             Ghevar   
4      5        Gulab jamun   
..   ...                ...   
247  248  Prawn malai curry   
249  250             Shukto   
250  251          Til Pitha   
251  252            Bebinca   
253  254          Mawa Bati   

                                           ingredients            diet  \
0                      Maida flour, yogurt, oil, sugar      vegetarian   
1                              Gram flour, ghee, sugar      vegetarian   
2         Carrots, milk, sugar, ghee, cashews, raisins      vegetarian   
3    Flour, ghee, kewra, milk, clarified butter, su...      vegetarian   
4    Milk powder, plain flour, baking powder, ghee,...      vegetarian   
..                                                 ...             ...   
247      Coconut milk, prawns, garlic, turmeric, sugar  non vegetarian   
249  Green beans, bitter gourd, ridge gourd, banana...      vegetarian   
250            Glutinous rice, black sesame seeds, gur      vegetarian   
251  Coconut milk, egg yolks, clarified butter, all...      vegetarian   
253  Milk powder, dry fruits, arrowroot powder, all...      vegetarian   

     prep_time  cook_time flavor_profile       course           state  \
0           45         25          sweet      dessert     West Bengal   
1           80         30          sweet      dessert       Rajasthan   
2           15         60          sweet      dessert          Punjab   
3           15         30          sweet      dessert       Rajasthan   
4           15         40          sweet      dessert     West Bengal   
..         ...        ...            ...          ...             ...   
247         15         50          spicy  main course     West Bengal   
249         10         20          spicy  main course     West Bengal   
250          5         30          sweet      dessert           Assam   
251         20         60          sweet      dessert             Goa   
253         20         45          sweet      dessert  Madhya Pradesh   

         region  
0          East  
1          West  
2         North  
3          West  
4          East  
..          ...  
247        East  
249        East  
250  North East  
251        West  
253     Central  

[225 rows x 10 columns]

### 2_8. 결손 데이터 처리하기
* isna(), dropna(), fillna()

In [169]:
# 파일 로딩 (hk_221206_na.csv)
df_hk_na = pd.read_csv('./data/hk_221206_na.csv')


In [174]:
# isna()
print(df_hk_na.isna().sum())
df_hk_na.info()

name            0
jumin7          0
gender          0
height          0
age            16
blood_type     16
company         0
grades          0
salary         16
expenditure     0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   name         250 non-null    object 
 1   jumin7       250 non-null    object 
 2   gender       250 non-null    object 
 3   height       250 non-null    float64
 4   age          234 non-null    float64
 5   blood_type   234 non-null    object 
 6   company      250 non-null    object 
 7   grades       250 non-null    object 
 8   salary       234 non-null    float64
 9   expenditure  250 non-null    int64  
dtypes: float64(3), int64(1), object(6)
memory usage: 19.7+ KB


In [183]:
# dropna()
print(len(df_hk_na.dropna(how = 'any')))
print(len(df_hk_na.dropna(how = 'all')))

# any : 한개라도 있으면 행 삭제 , all :모든 값이 결손값이면 삭제

234
250


In [189]:
df_hk_na.isna().sum()

name            0
jumin7          0
gender          0
height          0
age            16
blood_type     16
company         0
grades          0
salary         16
expenditure     0
dtype: int64

In [190]:
df_hk_na.dropna(subset=['salary'])

name    jumin7 gender  height   age blood_type company grades  salary  \
1     hkd10  900303-2      F   169.4  31.0          A       A      B  4720.0   
2    hkd100  681205-2      F   168.3  55.0          A       A      B  7280.0   
5    hkd103  910215-2      F   150.2  30.0          A       B      A  3290.0   
7    hkd105  980717-2      F   163.4  23.0          B       B      B  3080.0   
8    hkd106  970818-1      M   186.3  24.0         AB       B      C  3110.0   
..      ...       ...    ...     ...   ...        ...     ...    ...     ...   
244   hkd94  720614-1      M   174.1  49.0          O       A      B  8540.0   
245   hkd95  730710-2      F   157.8  50.0          A       A      A  6990.0   
246   hkd96  720805-2      F   150.4  51.0          O       A      A  7110.0   
247   hkd97  710929-1      M   172.4  52.0          A       A      B  8000.0   
249   hkd99  691115-2      F   152.6  54.0          B       A      B  7470.0   

     expenditure  
1           2970  
2           5905  
5           1915  
7           1330  
8           2360  
..           ...  
244         7165  
245         4865  
246         4985  
247         6625  
249         6095  

[234 rows x 10 columns]

In [184]:
df_hk_na.dropna(subset=['age','blood_type','salary'])

name    jumin7 gender  height   age blood_type company grades  salary  \
1     hkd10  900303-2      F   169.4  31.0          A       A      B  4720.0   
2    hkd100  681205-2      F   168.3  55.0          A       A      B  7280.0   
5    hkd103  910215-2      F   150.2  30.0          A       B      A  3290.0   
7    hkd105  980717-2      F   163.4  23.0          B       B      B  3080.0   
8    hkd106  970818-1      M   186.3  24.0         AB       B      C  3110.0   
..      ...       ...    ...     ...   ...        ...     ...    ...     ...   
244   hkd94  720614-1      M   174.1  49.0          O       A      B  8540.0   
245   hkd95  730710-2      F   157.8  50.0          A       A      A  6990.0   
246   hkd96  720805-2      F   150.4  51.0          O       A      A  7110.0   
247   hkd97  710929-1      M   172.4  52.0          A       A      B  8000.0   
249   hkd99  691115-2      F   152.6  54.0          B       A      B  7470.0   

     expenditure  
1           2970  
2           5905  
5           1915  
7           1330  
8           2360  
..           ...  
244         7165  
245         4865  
246         4985  
247         6625  
249         6095  

[234 rows x 10 columns]

In [198]:
# fillna()
# df_hk_na['age'].fillna(20)
df_hk_na['age'].fillna(value = df_hk_na['age'].mean())

df_hk_na['blood_type'].fillna('K')

0      K
1      A
2      A
3      K
4      K
      ..
245    A
246    O
247    A
248    K
249    B
Name: blood_type, Length: 250, dtype: object

## Quiz 8

(실습문제 유형5을 사용하여, : phone.csv (구분자:  “,” , 105,828 Rows, 10 Columns)

1) 단계 1-1. 데이터 중 테스트 결과(TestResult)가 SUCCESS이고 신호 강도(Signal) 값이 결측치(null, N/A 등)가 아닌 데이터만 추출

In [44]:
df_phone = pd.read_csv('./data/phone.csv')
df_phone.isna().sum()
df_phone.dropna(subset='Signal').loc[df_phone['TestResult']=='SUCCESS',:]
df_phone.dropna(subset='Signal').loc[df_phone['TestResult']=='SUCCESS',:].isna().sum()

Date                   0
Signal                 0
Speed                  0
Distance           10185
Manufacturer      105137
TestResult             0
TestTechnology         0
SetupTime              0
MOS                    0
Acceptability     100149
dtype: int64

In [199]:
df_phone = pd.read_csv('./data/phone.csv')

In [214]:
df_phone.loc[df_phone['TestResult'] == 'SUCCESS',:].dropna(subset = 'Signal')

Date  Signal      Speed  Distance Manufacturer TestResult  \
0        2017-07-01 0:00   -61.0  68.800003   1048.60     motorola    SUCCESS   
1        2017-07-01 0:02   -61.0  68.769997   1855.54          LGE    SUCCESS   
2        2017-07-01 0:05   -71.0  69.169998   1685.62     motorola    SUCCESS   
3        2017-07-01 0:08   -65.0  69.279999   1770.92          LGE    SUCCESS   
4        2017-07-01 0:10  -103.0   0.820000    256.07     motorola    SUCCESS   
...                  ...     ...        ...       ...          ...        ...   
105823  2017-10-31 23:34  -114.0  -1.000000   1149.34          NaN    SUCCESS   
105824  2017-10-31 23:38  -111.0  -1.000000   1177.42          NaN    SUCCESS   
105825  2017-10-31 23:43  -111.0   0.800000   1159.05          NaN    SUCCESS   
105826  2017-10-31 23:48  -111.0  -1.000000   1153.14          NaN    SUCCESS   
105827  2017-10-31 23:50  -111.0  -1.000000   1153.14          NaN    SUCCESS   

       TestTechnology  SetupTime  MOS  Acceptability  
0                UMTS       0.56    2            0.0  
1                UMTS       0.45    3            1.0  
2                UMTS       0.51    2            0.0  
3                UMTS       0.00    1            0.0  
4                UMTS       3.35    4            1.0  
...               ...        ...  ...            ...  
105823            LTE       0.53    4            NaN  
105824            LTE       0.84    4            NaN  
105825            LTE       0.43    4            NaN  
105826            LTE       0.52    4            NaN  
105827            LTE       0.80    4            NaN  

[105147 rows x 10 columns]

### 2_9. sort, aggregation함수, groupby 

* sort_values()


In [46]:
# 파일 로딩
df_hk = pd.read_csv('./data/hk_221206.csv')
df_hk

name    jumin7 gender  height  age blood_type company grades  salary  \
0      hkd1  990623-2      F   161.9   22          A       A      A    4100   
1     hkd10  900303-2      F   169.4   31          A       A      B    4720   
2    hkd100  681205-2      F   168.3   55          A       A      B    7280   
3    hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4    hkd102  920123-1      M   188.6   29          O       B      F    4390   
..      ...       ...    ...     ...  ...        ...     ...    ...     ...   
245   hkd95  730710-2      F   157.8   50          A       A      A    6990   
246   hkd96  720805-2      F   150.4   51          O       A      A    7110   
247   hkd97  710929-1      M   172.4   52          A       A      B    8000   
248   hkd98  701024-1      M   166.7   53          O       A      B    8760   
249   hkd99  691115-2      F   152.6   54          B       A      B    7470   

     expenditure  
0           1975  
1           2970  
2           5905  
3           2935  
4           4015  
..           ...  
245         4865  
246         4985  
247         6625  
248         7385  
249         6095  

[250 rows x 10 columns]

In [48]:
# sort_values, 1개 column 정렬
df_hk.sort_values(by = 'age', ascending=False)

name    jumin7 gender  height  age blood_type company grades  salary  \
2    hkd100  681205-2      F   168.3   55          A       A      B    7280   
42   hkd137  681231-1      M   182.9   55          A       B      B    8460   
207   hkd60  681202-1      M   186.0   55          O       A      B    9440   
231   hkd82  681204-1      M   174.0   55          A       A      B    9310   
224   hkd76  681203-1      M   173.6   55          O       A      B    9120   
..      ...       ...    ...     ...  ...        ...     ...    ...     ...   
118  hkd205  990624-2      F   160.3   22          A       C      A    5040   
138  hkd223  990625-1      M   169.3   22          A       C      B    4970   
6    hkd104  990623-1      M   176.0   22          A       B      A    3750   
0      hkd1  990623-2      F   161.9   22          A       A      A    4100   
164  hkd247  000526-3      M   189.4   20          A       C      B    5540   

     expenditure  
2           5905  
42          7335  
207         8315  
231         7935  
224         7995  
..           ...  
118         2915  
138         3220  
6           2375  
0           1975  
164         4165  

[250 rows x 10 columns]

In [49]:
# n개 column 정렬  ['blood_type', 'age']
df_hk.sort_values(by = ['blood_type','age'], ascending=False)

name    jumin7 gender  height  age blood_type company grades  salary  \
207   hkd60  681202-1      M   186.0   55          O       A      B    9440   
224   hkd76  681203-1      M   173.6   55          O       A      B    9120   
41   hkd136  690111-2      F   164.7   54          O       B      C    6440   
177   hkd33  691111-2      F   166.8   54          O       A      A    7520   
204   hkd58  701021-1      M   188.0   53          O       A      B    8000   
..      ...       ...    ...     ...  ...        ...     ...    ...     ...   
0      hkd1  990623-2      F   161.9   22          A       A      A    4100   
6    hkd104  990623-1      M   176.0   22          A       B      A    3750   
118  hkd205  990624-2      F   160.3   22          A       C      A    5040   
138  hkd223  990625-1      M   169.3   22          A       C      B    4970   
164  hkd247  000526-3      M   189.4   20          A       C      B    5540   

     expenditure  
207         8315  
224         7995  
41          5315  
177         5395  
204         6875  
..           ...  
0           1975  
6           2375  
118         2915  
138         3220  
164         4165  

[250 rows x 10 columns]

In [51]:
# n개 column 정렬, ascending(True/False) 적용
df_hk.sort_values(by = ['blood_type','age'], ascending=[True,False])

name    jumin7 gender  height  age blood_type company grades  salary  \
2    hkd100  681205-2      F   168.3   55          A       A      B    7280   
42   hkd137  681231-1      M   182.9   55          A       B      B    8460   
178   hkd34  681201-1      M   179.6   55          A       A      C    9430   
231   hkd82  681204-1      M   174.0   55          A       A      B    9310   
205   hkd59  691112-1      M   174.2   54          A       A      B    8100   
..      ...       ...    ...     ...  ...        ...     ...    ...     ...   
206    hkd6  941105-2      F   156.3   27          O       A      F    4160   
9    hkd107  960909-1      M   181.8   25          O       B      B    3230   
121  hkd208  960910-2      F   165.8   25          O       C      B    5710   
141  hkd226  960911-1      M   172.4   25          O       C      B    5550   
184    hkd4  960809-1      M   177.6   25          O       A      B    4450   

     expenditure  
2           5905  
42          7335  
178         8680  
231         7935  
205         6975  
..           ...  
206         3785  
9           1480  
121         3960  
141         4425  
184         3075  

[250 rows x 10 columns]

* aggregation (집계함수)

In [52]:
# 1개 column 에 대한 aggregation
df_hk['age'].mean()

39.24

In [56]:
# n개 column 에 대한 aggregation
df_hk[['age','salary']].agg(['mean','median','min','max','count'])

age    salary
mean     39.24   6357.48
median   39.00   6100.00
min      20.00   3080.00
max      55.00  11990.00
count   250.00    250.00

In [57]:
# n개 column 에 대한 n개 aggregation



age         39.24
salary    6100.00
dtype: float64

In [64]:
# n개 column 에 대한 column별 aggregation (dict형태로 입력)
df_hk[['age','salary']].agg({'age':'mean', 'salary':'median'})

age         39.24
salary    6100.00
dtype: float64

In [59]:
# 1개 column에 2개 이상 aggregation을 적용하면 마지막 aggregation이 적용
df_hk[['age','salary']].agg({'age':'mean', 'age':'max', 'salary':'median'})
# age:max만먹는다.

age         55.0
salary    6100.0
dtype: float64

In [ ]:
# 1개 column에 2개 이상 aggregation 적용 방법
df_hk[['age','salary']].agg({'age':'mean', 'age':'max', 'salary':'median'})

* groupby()

In [63]:
# 1개 column 에 대한 groupby
df_hk.groupby('company')['salary','age'].mean()
df_hk.groupby(['company','blood_type'])['salary','age'].mean()

salary        age
company blood_type                        
A       A           6635.294118  43.647059
        AB          6374.545455  42.272727
        B           6291.818182  42.590909
        O           6609.393939  43.636364
B       A           5383.235294  38.852941
        AB          5248.333333  37.500000
        B           5430.952381  39.476190
        O           5344.848485  38.878788
C       A           7725.625000  31.000000
        AB          7953.333333  32.000000
        B           8073.636364  31.727273
        O           8267.058824  33.176471

In [ ]:
# n개 column 에 대한 groupby 


* groupby() + aggregation

In [65]:
# groupby
df_hk.groupby(['blood_type','company'])['salary','age'].mean()

salary        age
blood_type company                        
A          A        6635.294118  43.647059
           B        5383.235294  38.852941
           C        7725.625000  31.000000
AB         A        6374.545455  42.272727
           B        5248.333333  37.500000
           C        7953.333333  32.000000
B          A        6291.818182  42.590909
           B        5430.952381  39.476190
           C        8073.636364  31.727273
O          A        6609.393939  43.636364
           B        5344.848485  38.878788
           C        8267.058824  33.176471

In [72]:
# n개 groupby + n개 aggregation(1개 column)
df_hk.groupby(['company','blood_type'])['age'].agg(['mean','max'])

mean  max
company blood_type                
A       A           43.647059   55
        AB          42.272727   54
        B           42.590909   54
        O           43.636364   55
B       A           38.852941   55
        AB          37.500000   51
        B           39.476190   50
        O           38.878788   54
C       A           31.000000   44
        AB          32.000000   42
        B           31.727273   41
        O           33.176471   45

In [73]:
# n개 groupby + n개 aggregation(column별 동일 aggregation)
df_hk.groupby(['company','blood_type'])['age','salary'].agg(['mean','max','median'])

age                  salary               
                         mean max median         mean    max  median
company blood_type                                                  
A       A           43.647059  55   45.5  6635.294118   9430  6725.0
        AB          42.272727  54   43.0  6374.545455   8730  6530.0
        B           42.590909  54   43.0  6291.818182   8860  5995.0
        O           43.636364  55   45.0  6609.393939   9440  6610.0
B       A           38.852941  55   38.5  5383.235294   8460  5400.0
        AB          37.500000  51   38.0  5248.333333   7460  5370.0
        B           39.476190  50   40.0  5430.952381   7420  6010.0
        O           38.878788  54   38.0  5344.848485   7420  5160.0
C       A           31.000000  44   31.0  7725.625000  11990  6915.0
        AB          32.000000  42   33.0  7953.333333  11080  8490.0
        B           31.727273  41   32.0  8073.636364  11720  7520.0
        O           33.176471  45   34.0  8267.058824  11810  8050.0

In [77]:
# n개 groupby + n개 aggregation(column별 다른 aggregation)
df_hk.groupby(['company','blood_type'])['age','salary'].agg({'age' : 'mean', 'salary':'median'})

age  salary
company blood_type                   
A       A           43.647059  6725.0
        AB          42.272727  6530.0
        B           42.590909  5995.0
        O           43.636364  6610.0
B       A           38.852941  5400.0
        AB          37.500000  5370.0
        B           39.476190  6010.0
        O           38.878788  5160.0
C       A           31.000000  6915.0
        AB          32.000000  8490.0
        B           31.727273  7520.0
        O           33.176471  8050.0

## Quiz 9

1) iris.cvs의 column('species')별로 'sepal_length' , 'sepal_width')의 평균, 중앙값, 최대값을 구하시오

In [85]:
df_iris = pd.read_csv('./data/iris.csv')
df_iris.groupby(['species'])['sepal_length','sepal_width'].agg(['mean','median','max'])


sepal_length             sepal_width            
                   mean median  max        mean median  max
species                                                    
setosa            5.006    5.0  5.8       3.428    3.4  4.4
versicolor        5.936    5.9  7.0       2.770    2.8  3.4
virginica         6.588    6.5  7.9       2.974    3.0  3.8

## 2_10. DataFrame의 병합 (join)
* concat

In [87]:
# 파일 로딩
df_up = df_hk.iloc[:5]
df_up

name    jumin7 gender  height  age blood_type company grades  salary  \
0    hkd1  990623-2      F   161.9   22          A       A      A    4100   
1   hkd10  900303-2      F   169.4   31          A       A      B    4720   
2  hkd100  681205-2      F   168.3   55          A       A      B    7280   
3  hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4  hkd102  920123-1      M   188.6   29          O       B      F    4390   

   expenditure  
0         1975  
1         2970  
2         5905  
3         2935  
4         4015

In [97]:
df_down = df_hk.iloc[-5:]
df_left = df_hk.loc[:5,:'age']
df_right = df_hk.loc[:5,'blood_type':]

In [92]:
df_right

blood_type company grades  salary  expenditure
0          A       A      A    4100         1975
1          A       A      B    4720         2970
2          A       A      B    7280         5905
3         AB       B      B    4060         2935
4          O       B      F    4390         4015
5          A       B      A    3290         1915

In [98]:
# concat 실습 파일 생성
pd.concat([df_up,df_down],axis = 0)

name    jumin7 gender  height  age blood_type company grades  salary  \
0      hkd1  990623-2      F   161.9   22          A       A      A    4100   
1     hkd10  900303-2      F   169.4   31          A       A      B    4720   
2    hkd100  681205-2      F   168.3   55          A       A      B    7280   
3    hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4    hkd102  920123-1      M   188.6   29          O       B      F    4390   
245   hkd95  730710-2      F   157.8   50          A       A      A    6990   
246   hkd96  720805-2      F   150.4   51          O       A      A    7110   
247   hkd97  710929-1      M   172.4   52          A       A      B    8000   
248   hkd98  701024-1      M   166.7   53          O       A      B    8760   
249   hkd99  691115-2      F   152.6   54          B       A      B    7470   

     expenditure  
0           1975  
1           2970  
2           5905  
3           2935  
4           4015  
245         4865  
246         4985  
247         6625  
248         7385  
249         6095

In [99]:
pd.concat([df_left,df_right],axis = 1)

name    jumin7 gender  height  age blood_type company grades  salary  \
0    hkd1  990623-2      F   161.9   22          A       A      A    4100   
1   hkd10  900303-2      F   169.4   31          A       A      B    4720   
2  hkd100  681205-2      F   168.3   55          A       A      B    7280   
3  hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4  hkd102  920123-1      M   188.6   29          O       B      F    4390   
5  hkd103  910215-2      F   150.2   30          A       B      A    3290   

   expenditure  
0         1975  
1         2970  
2         5905  
3         2935  
4         4015  
5         1915

In [ ]:
# concat (row), axis = 0 default 


In [ ]:
# concat (column)  axis = 1


* merge

In [100]:
# merge 실습 파일 생성
df_a = df_hk.iloc[:5, :2]
df_b = df_hk.iloc[3:7, :3]

In [105]:
# merge  (inner join default)
pd.merge(how = 'inner',left= df_a, right = df_b, left_on = 'name',right_on = 'name')

name  jumin7_x  jumin7_y gender
0  hkd101  931226-2  931226-2      F
1  hkd102  920123-1  920123-1      M

In [106]:
# merge   (left join)
pd.merge(how = 'left',left= df_a, right = df_b, left_on = 'name',right_on = 'name')

name  jumin7_x  jumin7_y gender
0    hkd1  990623-2       NaN    NaN
1   hkd10  900303-2       NaN    NaN
2  hkd100  681205-2       NaN    NaN
3  hkd101  931226-2  931226-2      F
4  hkd102  920123-1  920123-1      M

In [109]:
# merge   (outer join)
pd.merge(how = 'outer',left= df_a, right = df_b, left_on = 'name',right_on = 'name')

name  jumin7_x  jumin7_y gender
0    hkd1  990623-2       NaN    NaN
1   hkd10  900303-2       NaN    NaN
2  hkd100  681205-2       NaN    NaN
3  hkd101  931226-2  931226-2      F
4  hkd102  920123-1  920123-1      M
5  hkd103       NaN  910215-2      F
6  hkd104       NaN  990623-1      M

### 2_11. column내 값 변경
* replace
* map

In [133]:
df_hk = pd.read_csv('./data/hk_221206.csv')

In [135]:
# replace (1개 값 변경)
df_hk['gender'] = df_hk['gender'].replace({'F':'female','M':'male'})

In [136]:
# replace (n개 값 변경)

# df_hk = df_hk['gender'].map({'F':'Female', 'M':'Male'})

df_hk

name    jumin7  gender  height  age blood_type company grades  salary  \
0      hkd1  990623-2  female   161.9   22          A       A      A    4100   
1     hkd10  900303-2  female   169.4   31          A       A      B    4720   
2    hkd100  681205-2  female   168.3   55          A       A      B    7280   
3    hkd101  931226-2  female   155.3   28         AB       B      B    4060   
4    hkd102  920123-1    male   188.6   29          O       B      F    4390   
..      ...       ...     ...     ...  ...        ...     ...    ...     ...   
245   hkd95  730710-2  female   157.8   50          A       A      A    6990   
246   hkd96  720805-2  female   150.4   51          O       A      A    7110   
247   hkd97  710929-1    male   172.4   52          A       A      B    8000   
248   hkd98  701024-1    male   166.7   53          O       A      B    8760   
249   hkd99  691115-2  female   152.6   54          B       A      B    7470   

     expenditure  
0           1975  
1           2970  
2           5905  
3           2935  
4           4015  
..           ...  
245         4865  
246         4985  
247         6625  
248         7385  
249         6095  

[250 rows x 10 columns]

In [137]:
# map (n개 값 변경)
df_hk['gender'] = df_hk['gender'].map({'female':'F', 'male':'M'})
df_hk

name    jumin7 gender  height  age blood_type company grades  salary  \
0      hkd1  990623-2      F   161.9   22          A       A      A    4100   
1     hkd10  900303-2      F   169.4   31          A       A      B    4720   
2    hkd100  681205-2      F   168.3   55          A       A      B    7280   
3    hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4    hkd102  920123-1      M   188.6   29          O       B      F    4390   
..      ...       ...    ...     ...  ...        ...     ...    ...     ...   
245   hkd95  730710-2      F   157.8   50          A       A      A    6990   
246   hkd96  720805-2      F   150.4   51          O       A      A    7110   
247   hkd97  710929-1      M   172.4   52          A       A      B    8000   
248   hkd98  701024-1      M   166.7   53          O       A      B    8760   
249   hkd99  691115-2      F   152.6   54          B       A      B    7470   

     expenditure  
0           1975  
1           2970  
2           5905  
3           2935  
4           4015  
..           ...  
245         4865  
246         4985  
247         6625  
248         7385  
249         6095  

[250 rows x 10 columns]

### 2_12. apply lambda 식으로 데이터 가공

In [ ]:
# 파일 로딩 
dh_hk[:2]


In [164]:
# apply lambda
df_hk['birthday'] = df_hk['jumin7'].apply(lambda x : '19'+x[:-2])
df_hk['birthday'] = df_hk['birthday'].astype('datetime64')
df_hk

name    jumin7 gender  height  age blood_type company grades  salary  \
0      hkd1  990623-2      F   161.9   22          A       A      A    4100   
1     hkd10  900303-2      F   169.4   31          A       A      B    4720   
2    hkd100  681205-2      F   168.3   55          A       A      B    7280   
3    hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4    hkd102  920123-1      M   188.6   29          O       B      F    4390   
..      ...       ...    ...     ...  ...        ...     ...    ...     ...   
245   hkd95  730710-2      F   157.8   50          A       A      A    6990   
246   hkd96  720805-2      F   150.4   51          O       A      A    7110   
247   hkd97  710929-1      M   172.4   52          A       A      B    8000   
248   hkd98  701024-1      M   166.7   53          O       A      B    8760   
249   hkd99  691115-2      F   152.6   54          B       A      B    7470   

     expenditure   birthday  
0           1975 1999-06-23  
1           2970 1990-03-03  
2           5905 1968-12-05  
3           2935 1993-12-26  
4           4015 1992-01-23  
..           ...        ...  
245         4865 1973-07-10  
246         4985 1972-08-05  
247         6625 1971-09-29  
248         7385 1970-10-24  
249         6095 1969-11-15  

[250 rows x 11 columns]

### 2_13. 값 등급화, 분류
* np.where
* cut

In [169]:
# np.where 2개
# np.where(조건, True, False)

np.where(df_hk['age'] <= 30,'30이하' ,'30이상' )[:5]

array(['30이하', '30이상', '30이상', '30이하', '30이하'], dtype='<U4')

In [172]:
# np.where 3개
# np.where(조건1, True, False)
# np.where(조건1, True, 
#                 np.where(조건2, True, False)
np.where(df_hk['age'] <= 30,'30이하' ,
          np.where(df_hk['age']<40, '40대','50대이상'))[:10]

array(['30이하', '40대', '50대이상', '30이하', '30이하', '30이하', '30이하', '30이하',
       '30이하', '30이하'], dtype='<U5')

In [173]:
# cut
pd.cut(x = df_hk['age'], bins = [0,20,30,40,100], 
           labels = ['10대', '20대', '30대', '40대이상'])

0        20대
1        30대
2      40대이상
3        20대
4        20대
       ...  
245    40대이상
246    40대이상
247    40대이상
248    40대이상
249    40대이상
Name: age, Length: 250, dtype: category
Categories (4, object): ['10대' < '20대' < '30대' < '40대이상']

In [178]:

df_hk

name    jumin7 gender  height  age blood_type company grades  salary  \
0      hkd1  990623-2      F   161.9   22          A       A      A    4100   
1     hkd10  900303-2      F   169.4   31          A       A      B    4720   
2    hkd100  681205-2      F   168.3   55          A       A      B    7280   
3    hkd101  931226-2      F   155.3   28         AB       B      B    4060   
4    hkd102  920123-1      M   188.6   29          O       B      F    4390   
..      ...       ...    ...     ...  ...        ...     ...    ...     ...   
245   hkd95  730710-2      F   157.8   50          A       A      A    6990   
246   hkd96  720805-2      F   150.4   51          O       A      A    7110   
247   hkd97  710929-1      M   172.4   52          A       A      B    8000   
248   hkd98  701024-1      M   166.7   53          O       A      B    8760   
249   hkd99  691115-2      F   152.6   54          B       A      B    7470   

     expenditure  
0           1975  
1           2970  
2           5905  
3           2935  
4           4015  
..           ...  
245         4865  
246         4985  
247         6625  
248         7385  
249         6095  

[250 rows x 10 columns]

### 2_14. 날짜 변수 처리 (datetime)

In [174]:
import datetime

In [183]:
df_hk['birth_day'] = pd.to_datetime(df_hk['jumin7'],format = '%y%m%d-%w')

In [ ]:
# pd.to_datetime


In [196]:
# astype('datetime64')
df_hk

name     jumin7 gender  height  age blood_type company grades  salary  \
0      hkd1 1999-06-23      F   161.9   22          A       A      A    4100   
1     hkd10 1990-03-03      F   169.4   31          A       A      B    4720   
2    hkd100 2068-12-05      F   168.3   55          A       A      B    7280   
3    hkd101 1993-12-26      F   155.3   28         AB       B      B    4060   
4    hkd102 1992-01-23      M   188.6   29          O       B      F    4390   
..      ...        ...    ...     ...  ...        ...     ...    ...     ...   
245   hkd95 1973-07-10      F   157.8   50          A       A      A    6990   
246   hkd96 1972-08-05      F   150.4   51          O       A      A    7110   
247   hkd97 1971-09-29      M   172.4   52          A       A      B    8000   
248   hkd98 1970-10-24      M   166.7   53          O       A      B    8760   
249   hkd99 1969-11-15      F   152.6   54          B       A      B    7470   

     expenditure  birth_day  
0           1975 1999-06-23  
1           2970 1990-03-03  
2           5905 2068-12-05  
3           2935 1993-12-26  
4           4015 1992-01-23  
..           ...        ...  
245         4865 1973-07-10  
246         4985 1972-08-05  
247         6625 1971-09-29  
248         7385 1970-10-24  
249         6095 1969-11-15  

[250 rows x 11 columns]

In [195]:
# datetime.datetime.strptime
df_hk['jumin7'] = df_hk['jumin7'].apply(lambda x : x[0:6]).apply(lambda x : datetime.datetime.strptime(x, '%y%m%d'))

In [198]:
# datetime 활용
df_hk['birth_day'].dt.year
df_hk['birth_day'].dt.month
df_hk['birth_day'].dt.day
df_hk['birth_day'].dt.weekday
df_hk['birth_day'].dt.day_name()
df_hk.dtypes

name                   object
jumin7         datetime64[ns]
gender                 object
height                float64
age                     int64
blood_type             object
company                object
grades                 object
salary                  int64
expenditure             int64
birth_day      datetime64[ns]
dtype: object

Quiz 7 (실습문제 유형5을 사용하여, : phone.csv (구분자: “,” , 105,828 Rows, 10 Columns)

1) 단계 1-1. 데이터 중 테스트 결과(TestResult)가 SUCCESS이고 신호 강도(Signal) 값이 결측치(null, N/A 등)가 아닌 데이터만 추출

In [10]:
# 파일 로딩
df = pd.read_csv('./data/phone.csv')

In [6]:
import pandas as pd

In [32]:
df['TestResult'].value_counts()

SUCCESS                 105148
FAILURE - DROP CALL        644
FAILURE - SETUP FAIL        36
Name: TestResult, dtype: int64

In [25]:
# 단계 1-1. 데이터 중 테스트 결과(TestResult)가 SUCCESS

df.loc[df['TestResult'] == 'SUCCESS']

Date  Signal      Speed  Distance Manufacturer TestResult  \
0        2017-07-01 0:00   -61.0  68.800003   1048.60     motorola    SUCCESS   
1        2017-07-01 0:02   -61.0  68.769997   1855.54          LGE    SUCCESS   
2        2017-07-01 0:05   -71.0  69.169998   1685.62     motorola    SUCCESS   
3        2017-07-01 0:08   -65.0  69.279999   1770.92          LGE    SUCCESS   
4        2017-07-01 0:10  -103.0   0.820000    256.07     motorola    SUCCESS   
...                  ...     ...        ...       ...          ...        ...   
105823  2017-10-31 23:34  -114.0  -1.000000   1149.34          NaN    SUCCESS   
105824  2017-10-31 23:38  -111.0  -1.000000   1177.42          NaN    SUCCESS   
105825  2017-10-31 23:43  -111.0   0.800000   1159.05          NaN    SUCCESS   
105826  2017-10-31 23:48  -111.0  -1.000000   1153.14          NaN    SUCCESS   
105827  2017-10-31 23:50  -111.0  -1.000000   1153.14          NaN    SUCCESS   

       TestTechnology  SetupTime  MOS  Acceptability  
0                UMTS       0.56    2            0.0  
1                UMTS       0.45    3            1.0  
2                UMTS       0.51    2            0.0  
3                UMTS       0.00    1            0.0  
4                UMTS       3.35    4            1.0  
...               ...        ...  ...            ...  
105823            LTE       0.53    4            NaN  
105824            LTE       0.84    4            NaN  
105825            LTE       0.43    4            NaN  
105826            LTE       0.52    4            NaN  
105827            LTE       0.80    4            NaN  

[105148 rows x 10 columns]

In [28]:
# 신호 강도(Signal) 값이 결측치(null, N/A 등)가 아닌 데이터만 추출

df.loc[(df['TestResult'] == 'SUCCESS') & (df['Signal'] != 'null')]['TestResult'].count()

105148

In [18]:
df['TestResult'].value_counts()


SUCCESS                 105148
FAILURE - DROP CALL        644
FAILURE - SETUP FAIL        36
Name: TestResult, dtype: int64